# Site settings
title: Kevin @ Work
description: > # this means to ignore newlines until "baseurl:"
  Googler working on Dart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://work2.j832.com" # the base hostname & protocol for your site
twitter_username: kevmoo
github_username:  kevmoo

# To match blogger style
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
