# Site settings
title: Kevin @ Work
description: > # this means to ignore newlines until "baseurl:"
  Googler working on Dart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://work.j832.com" # the base hostname & protocol for your site
twitter_username: kevmoo
github_username:  kevmoo

# To match blogger style
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

google_analytics_id: UA-3441863-2

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
